language: android
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-22
  - extra-android-m2repository
env:
- GRADLE_OPTS="-XX:MaxPermSize=512m"
before_install:
- openssl aes-256-cbc -K $encrypted_9d80a7fa7284_key -iv $encrypted_9d80a7fa7284_iv -in medic-official.keystore.enc -out medic-official.keystore -d
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
stages:
- name: test
- name: build
  if: tag IS present
jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: build
      script: make travis
before_script:
- yes | sdkmanager 'platforms;android-28'
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: eyzgNqmrlLjdEQuzhTP/I8Nbm8srA6hFfvRJQpCG8C1zaeDjwABmr9sNjz9Mb+ojIU0j5v7oU/2qEggi5jVu8PCnfSwASvyyatzluK3XsI8WbdvYj5xtQGKAGAK15yp1OLh5vbbWz3TWDRSUuFNSKAd4EhHjYk6+CIn3WypWVt6/9PI+yV8Ig/scFoE5HtSgNHZ9ZKhb4lz7zTDVoLQqPo5E9HLWizoehIYt9lVNy5leqEmIrVBYJsb1uCrAcK2ZM4Av2C/Vwk/+ynTF2IGIuR4Ms2/O/8LVW88m6NXLu/DyoR9G87LSeF8j51W+zsnHdXtJqZDBFQPP/h8c7iqhzHDqNlUnuLNJ3RHd2ezElnhOV56aJ0Nz2ra+FXJkuy98rBv8/i5LRx7+n6zcmzosgeRiX25zzifggHFtImcdqsuTfmnTgVjC14fMHOgmDgE6UTmG5gVZk7+6BadatTMVVjYPiU1bWIX2yaW4Hye3TxxVjqWj7vOwIi1xomvLA0k/lWhp42ohlZ78nJLLKVLNFAfkftTbzEJSZjUfrVDD/Q2p2zGdgi6kYoXKcXOyPKLKcpUjgHcGUyWNBaqHzCk2iEdSOHz6yPwDdggDXI1GLI9V6fFeLJZ1QJunT9hfiiWLpTn4PaCE5HPiylkxmgr0xboETPwpFOR+rUuyH/ajpkQ=
  file_glob: true
  file: ./build/outputs/apk/**/*.apk
  on:
    tags: true
    repo: medic/medic-collect
    branch: master
