language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
before_deploy:
  - "mkdir -p build/publish/travis-${TRAVIS_BUILD_NUMBER}"
  - "cp build/outputs/apk/*-release.apk build/publish/travis-${TRAVIS_BUILD_NUMBER}"
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: ${s3_access_id}
  secret_access_key:
    secure: ${s3_access_secret}
  bucket: medic-mobile
  local_dir: build/publish
  upload-dir: builds/medic-collect
  acl: public_read
  on:
    repo: ${TRAVIS_REPO_SLUG}
after_success:
  - git config --global user.email "dev@medicmobile.org"
  - git config --global user.name "Travis CI"
  - git tag travis-$TRAVIS_BUILD_NUMBER
  - git push --tags "https://${github_auth}@github.com/${TRAVIS_REPO_SLUG}" >/dev/null 2>/dev/null
branches:
  except:
      - /^travis-.*/
